- webapp/package.json
- webapp/yarn.lock
> chore: add storybook deployer

- webapp/.editorconfig
added two rules:
- trim whitespaces on the end of the line
- ensure all files are UTF-8
> chore: improve editorconfig file

- webapp/src/components/Button/colors.css
- webapp/src/components/Button/index.js
- webapp/src/components/Button/properties.css
- webapp/src/components/Button/style.css
- webapp/src/styles/colors.css
- webapp/stories/Button/index.js
- webapp/stories/Button/style.css
I removed the dark theme because this should be implemented in the PR of deploying the themes.
Closes: #38
> Fix button style

- README.md
add info to help users implement the checkout modal in their ecommerces
this can be improved later and can even change depending on how the
project will evolve
> readme: add details about implementing

- webapp/src/components/Input/properties.css
- webapp/src/components/Input/style.css
- webapp/stories/FormFields/examples/Input.js
closes #42 
updated
- border solid instead of dashed on disable
- border color and size on focus 
- label color 
- error label/caret color
> input: update component styles

- webapp/README.md
closes #13 as we don't need to keep an open issue for that kinda of
information
> chore: update readme

- webapp/public/custom.html
- webapp/src/api/simple.js
- webapp/src/components/App/App.test.js
- webapp/src/components/Dropdown/Dropdown.test.js
- webapp/src/components/Dropdown/index.js
- webapp/src/components/Dropdown/properties.css
- webapp/src/components/Dropdown/style.css
- webapp/src/components/Input/index.js
- webapp/src/components/Input/style.css
- webapp/src/pages/AddressData/index.js
- webapp/src/pages/AddressData/states.js
- webapp/src/pages/CustomerData/index.js
- webapp/stories/FormFields/examples/Dropdown.js
- webapp/stories/FormFields/index.js
Primeira versão da página de billing, foi necessário adicionar um componente novo para o estado.
Estou abrindo uma issue para adicionar a lógica de preenchimento automático quando o CEP for digitado 
closes #49
> Billing page

- README.md
- webapp/package.json
O novo nome é **Artis**. 
Ainda precisamos de um slogan.
closes: #29
> Novo nome do projeto

- webapp/src/components/Button/Button.test.js
- webapp/src/components/Footer/Footer.test.js
- webapp/src/components/ProgressBar/ProgressBar.test.js
- webapp/src/components/ProgressBar/index.js
> Add testing

- webapp/.storybook/addons.js
- webapp/.storybook/config.js
- webapp/.storybook/themeDecorator.js
add themedecorator to all stories on storybook
> theme: add theme decorator to storybook

- webapp/src/containers/AddressFormContainer/index.js
- webapp/src/theme-pagarme/address-form/index.css
- webapp/src/theme-pagarme/button/index.css
- webapp/src/theme-pagarme/button/properties.css
- webapp/src/theme-pagarme/colors.css
- webapp/src/theme-pagarme/colors/dark.css
- webapp/stories/Button/index.js
Resolves: [#23](https://github.com/pagarme/mercurio/issues/23)
- Fixed button colors;
- Fixed button spacing.
> button: fix css styles

- webapp/src/components/AddressOptions/index.js
- webapp/src/theme-pagarme/address-form/index.css
- webapp/src/theme-pagarme/address-options/index.css
- webapp/src/theme-pagarme/address-options/properties.css
- webapp/src/theme-pagarme/colors.css
- webapp/src/theme-pagarme/grid/index.css
- webapp/src/theme-pagarme/progress-bar/index.css
- webapp/src/theme-pagarme/progress-bar/properties.css
Closes: [#36](https://github.com/pagarme/mercurio/issues/36)
* Address options content has been updated;
* Progress bar background has changed to gradient;
* Removed last-child row margin-bottom.
> Pages: fix address options mobile layout

- README.md
Fixes broken URLs and badges that were referring to mundipagg's organization, instead of pagar.me's.
> Fix broken links on README

- webapp/package.json
- webapp/src/components/ErrorBoundary/ErrorReport.js
- webapp/src/components/ErrorBoundary/index.js
- webapp/src/components/Header/index.js
- webapp/src/containers/AddressForm/index.js
- webapp/src/index.js
- webapp/src/pages/Payment.js
- webapp/yarn.lock
This PR adds the initial Google Analytics configs.
Closes https://github.com/pagarme/mercurio/issues/39
> analytics: add initial configs

- webapp/src/components/ErrorInfo/index.js
- webapp/src/components/ProgressBar/ProgressBar.test.js
- webapp/src/components/ProgressBar/index.js
- webapp/src/components/SuccessInfo/index.js
- webapp/src/containers/AddressForm/index.js
- webapp/src/containers/Checkout/index.js
- webapp/src/pages/Billing.js
- webapp/src/pages/Confirmation.js
- webapp/src/pages/Customer.js
- webapp/src/pages/Payment.js
- webapp/src/pages/Shipping.js
- webapp/src/theme-pagarme/address-form/index.css
- webapp/src/theme-pagarme/address-form/properties.css
- webapp/src/utils/isBigScreen.js
- webapp/yarn.lock
Add callback to listen window `resize` event.
This callback adds the variable isBigScreen to the state of the application.
> Update resize strategy

- webapp/src/components/Footer/index.js
- webapp/src/components/ProgressBar/ProgressBar.test.js
- webapp/src/components/ProgressBar/index.js
- webapp/src/containers/AddressForm/index.js
- webapp/src/containers/Checkout/index.js
- webapp/src/pages/Billing.js
- webapp/src/pages/Shipping.js
- webapp/src/theme-pagarme/address-form/index.css
- webapp/src/theme-pagarme/billing-page/index.css
- webapp/src/theme-pagarme/billing-page/properties.css
- webapp/src/theme-pagarme/button/index.css
- webapp/src/theme-pagarme/checkout/index.css
- webapp/src/theme-pagarme/checkout/properties.css
- webapp/src/theme-pagarme/customer-page/index.css
- webapp/src/theme-pagarme/customer-page/properties.css
- webapp/src/theme-pagarme/footer/index.css
- webapp/src/theme-pagarme/header/index.css
- webapp/src/theme-pagarme/header/properties.css
- webapp/src/theme-pagarme/input/properties.css
- webapp/src/theme-pagarme/progress-bar/index.css
- webapp/src/theme-pagarme/progress-bar/properties.css
- webapp/src/theme-pagarme/switch/index.css
- webapp/src/theme-pagarme/switch/properties.css
Some layout adjusts.
1. Caret color.
2. Fix to resize when show scrollbar.
3. Remove title on mobile.
4. Fix progressbar step title on mobile
5. Update address form on mobile
Closes https://github.com/pagarme/mercurio/issues/42
> Some layout adjusts

- webapp/src/containers/AddressForm/index.js
- webapp/src/containers/Checkout/index.js
- webapp/src/pages/Shipping.js
- webapp/yarn.lock
1. Add shipping configs on shipping-page
**Before**
**After**
2. Add a handle to persist address in new address form.
> Fix shipping page

- webapp/package.json
- webapp/yarn.lock
i noticed we have several cases where we push to remote just for
realizing that the CI is broken
adding a precommit hook helps us running the tests everytime we commit
with no need to remember by ourselves
Closes #XXX 
> chore: add pre commit hook

- webapp/config/env.js
- webapp/src/components/ErrorBoundary/ErrorReport.js
- webapp/src/components/ErrorBoundary/index.js
Trigger will only works in production.
Closes [#40](https://github.com/pagarme/mercurio/issues/40)
> Add: Sentry

- webapp/config/webpack.config.prod.js
- webapp/scripts/build.js
Refactor production build script.
For test: https://github.com/augusto-jm-amaral/artis-build-test
Closes https://github.com/pagarme/mercurio/issues/46
> Build production

- webapp/src/components/LoadingInfo/index.js
- webapp/src/pages/Confirmation.js
- webapp/src/theme-pagarme/animations.css
- webapp/src/theme-pagarme/checkout/index.css
- webapp/src/theme-pagarme/loading-info/index.css
- webapp/src/theme-pagarme/loading-info/properties.css
I added a spinner on the loading page.
**Desktop**
**Mobile**
> Loading page

- jest.config.js
- package.json
- src/components/Footer/index.js
- stories/__snapshots__/storyshots.test.js.snap
- stories/storyshots.test.js
- yarn.lock
remember to update it when necessary using `u` when running `yarn test`
Closes https://github.com/pagarme/mercurio/issues/51
> snapshot: add snapshot testing

- package.json
- src/components/Switch/Switch.test.js
- src/components/Switch/index.js
- src/store.js
- stories/Switch/index.js
- stories/__snapshots__/storyshots.test.js.snap
- yarn.lock
> chore: fix errors on build

- config/webpack.config.prod.js
- package.json
- yarn.lock
Add some improvements on build.
Closes: https://github.com/pagarme/mercurio/issues/46
> Build improvements

- config/robrowser/auth.js
- src/theme-pagarme/grid/index.css
It will make grid display `block`, to browsers with few implementations of flexbox.
**O.S**: OS X Sierra
**Browser**: Chrome 40
---
**O.S**: OS X Sierra
**Browser**: Safari 10.1
---
**O.S**: Windows 7
**Browser**: Chrome 40
---
**O.S**:  Windows 10
**Browser**:  IE 11
Closes [#55](https://github.com/pagarme/mercurio/issues/55)
> grid: update css

- public/index.html
- src/components/NormalizeCSS/index.js
- src/index.js
- src/theme-pagarme/index.js
- src/theme-pagarme/normalize.css
it will makes browsers render all elements more consistently
Closes https://github.com/pagarme/mercurio/issues/48
> css: add normalize

- .circleci/config.yml
- .storybook/addons.js
- config/webpack.config.prod.js
- package.json
- yarn.lock
Closes https://github.com/pagarme/mercurio/issues/72
> chore: add circleci integration

- .circleci/config.yml
Add circle ci deploy in integration
> add staging deploy

- public/index.html
- src/components/Cart/index.js
- src/containers/Checkout/index.js
- src/themes/default/cart/index.css
- src/themes/default/colors.css
Add purchase summary on the cart. Also added freight item.
When the freight value is `0`, the is substituted for word `Grátis`. 
- **Desktop Dark**
- **Desktop Light**
- **Mobile Dark**
- **Mobile Light**
Closes https://github.com/pagarme/mercurio/issues/71 
> Add purchase sumary

- src/themes/default/addressesPage/index.css
- src/themes/default/confirmationPage/index.css
- src/themes/default/footer/index.css
- src/themes/default/paymentPage/index.css
on mobile devices there were some distances that didn't need to be that
big
**página de pagamento:** 
antes: 
depois:
**página de confirmação:**
antes: 
depois: 
> cart-button: fix styles on mobile

- .circleci/config.yml
this feature remove cache from /latest/index.js in
published site when new version is published
> feat: add invalidation from cloudfront for cdn

- src/containers/Checkout/index.js
- src/pages/Addresses.js
- src/pages/Payment.js
- src/themes/default/dropdown/index.css
add placeholder and fix styles for both dark and light themes
Closes https://github.com/pagarme/mercurio/issues/81
> dropdown: fix styles and placeholder

- package.json
- src/components/Cart/index.js
- src/components/RadioGroup/RadioGroup.test.js
- src/components/RadioGroup/index.js
- src/containers/Checkout/index.js
- src/pages/Addresses.js
- src/themes/default/addressesPage/index.css
- src/themes/default/customerPage/index.css
- src/themes/default/index.js
- src/themes/default/radio-group/index.css
- yarn.lock
remove it from former-kit and bring the component to our project
also, fix the style (the vertical alignment)
also removes the former-kit dependency because we only need one component and we can't afford have that much of unnecessary dependencies on our project 
check build size improvement
**before:** 
+500Kb gziped
**after:**
300Kb gziped 
alignment
**before:**
**after:**
Closes https://github.com/pagarme/mercurio/issues/94
:rotating_light: Please review these items for a good pull request. :four_leaf_clover:
1. I've updated the project docs (if …
> radio-group: add new component

- src/pages/Payment/CreditCardAndBoleto.js
- src/pages/Payment/MultipleCreditCards.js
- src/pages/Payment/SwitchPayment.js
Closes https://github.com/pagarme/mercurio/issues/117
> button-text: update button text on last step

- src/index.js
- src/utils/strategies/pagarme.js
Closes https://github.com/pagarme/mercurio/issues/120
> chore: fix boleto keys

- src/components/Switch/index.js
- src/pages/Payment/BoletoForm.js
- src/pages/Payment/CreditCardAndBoleto.js
- src/pages/Payment/CreditCardForm.js
- src/pages/Payment/MultipleCreditCards.js
- src/themes/default/input/index.css
- src/themes/default/paymentPage/index.css
Closes [#115](https://github.com/pagarme/mercurio/issues/115)
This PR does'nt change the dropdown icon, because i don't have find any it seems right.
1 cartão - mobile
2 cartões - mobile
Cartão e Boleto - mobile
Cartão - tablet
> Credid card: update style

- src/components/Switch/index.js
- src/containers/Checkout/index.js
- src/pages/Payment/SwitchPayment.js
- src/pages/Payment/index.js
- src/themes/default/switch/index.css
* Works with Light theme;
* Border-right fixed.
Dark
Light
Closes [#109](https://github.com/pagarme/mercurio/issues/109)
> Switch: update styles

- src/components/SuccessInfo/index.js
- src/containers/Checkout/index.js
tem mais coisa inclusa aqui porque peguei do branch em https://github.com/pagarme/artis/pull/162 já que dependia pra eu fazer essa, quando ele for mergeado posso fazer um rebase, mas esse PR depende daquele ser mergeado 
já aproveitei pra tirar o botao de boleto pra enviar email, já que não temos o serviço ainda 
Closes https://github.com/pagarme/mercurio/issues/118
In a good pull …
> Success page

- config/webpack.config.prod.js
Remove svs from file-loader, using only babel-loader and svgr to load.
> Svgs were breaking the build

- public/index.html
- src/pages/Payment/MultipaymentOptions.js
- src/pages/Payment/index.js
- src/themes/default/paymentPage/index.css
Closes [#116](https://github.com/pagarme/mercurio/issues/116) 
> multi-payment: update styles

- src/components/ActionList/index.js
- src/components/SuccessInfo/index.js
- src/pages/Payment/BoletoForm.js
- src/pages/Payment/SwitchPayment.js
- src/themes/default/errorInfo/index.css
- src/themes/default/paymentPage/index.css
fixed the boleto screen, confirmation page, and some buttons behaviours
Closes https://github.com/pagarme/mercurio/issues/114
> boleto: fix boleto payment flow

- src/themes/default/dropdown/index.css
Closes https://github.com/pagarme/mercurio/issues/110
> dropdown: fix arrow position

- src/index.js
- src/pages/Payment/CreditCardForm.js
- src/utils/data/colors.js
- src/utils/helpers/createElement.js
when opening the modal the user can give us the target, or we can create
a default one
now in both cases we check if it exists, and if so, we don't create a
new one
😉
Closes https://github.com/pagarme/mercurio/issues/108
> checkout-wrapper: fix creation on open modal

- package.json
- src/index.js
- src/pages/Customer.js
- yarn.lock
I changed an example Grid and Row just to show how it has to be done, I won't replace all the Grid components in this PR as it is not the intention. 
Basically, for using our own theme for every component we need to match the expected classes in `former-kit`, so some components may need a little css refactoring before being replaced (that's why in the `Customer.js` file I didn't replace the  `Col` component)
Closes https://github.com/pagarme/mercurio/issues/142
1. I've …
> former-kit: add lib to the project

- .eslintrc
- src/components/ErrorInfo/index.js
- src/components/SuccessInfo/index.js
- src/pages/Addresses.js
- src/pages/Payment/BoletoForm.js
- src/pages/Payment/CreditCardForm.js
- src/utils/calculations/generateInstallments.js
- src/utils/data/errorMessages.js
- src/utils/validations/index.js
> chore: add new line max length eslint rule

- src/components/Footer/Footer.test.js
- src/components/Footer/index.js
- src/containers/Checkout/index.js
- src/images/escudo.svg
- src/themes/default/checkout/index.css
- src/themes/default/footer/index.css
- stories/Footer/index.js
update footer component to match the new style
(the content still needs to be fixed, but it's not this PR's intention)
Closes https://github.com/pagarme/mercurio/issues/133
> footer: update footer component

- src/components/Header/index.js
- src/themes/default/header/index.css
Closes [#146](https://github.com/pagarme/mercurio/issues/146)
> header: update logo style

- src/pages/Customer.js
- src/themes/default/colors.css
- src/themes/default/customerPage/index.css
- src/themes/default/input/index.css
now it's using purely flex box instead of wrapping in grids, rows and
cols
I didn't test it on mobile as we are still about to receive the new
layout, so this commit only updates the styles for what it should look
on the desktop
Closes https://github.com/pagarme/mercurio/issues/139
> customer-page: update layout

- public/assets/js/apiParameters.js
- src/utils/strategies/pagarme.js
Soft descriptor field was add to api. It already exists in the paymet api.
Closes https://github.com/pagarme/mercurio/issues/152
> API: add softDescriptor to boleto

- package.json
- src/components/Cart/index.js
- src/containers/Checkout/index.js
- src/pages/Addresses.js
- src/themes/default/addressesPage/index.css
- src/themes/default/checkout/index.css
- yarn.lock
Update address page layout.
Some problems with styles of other components are breaking de size, I create an issue about it https://github.com/pagarme/mercurio/issues/154.
**QA**
Closes https://github.com/pagarme/mercurio/issues/140 
> Update address page layout

- src/pages/Payment/SwitchPayment.js
- src/utils/helpers/changeInstallmentsToArray.js
- src/utils/helpers/helpers.test.js
- src/utils/helpers/modifyInstallments.js
Now the customer can pass installments like an object or array.
```
creditcard: {
invoiceDescriptor: 'Mercurio :)',
installments: {
initial: 2,
max: 10,
free: 3,
interestRate: [
{
installment: 3,
type: 'percentage',
value: 10,
},
{
installment: 6,
type: 'amount',
value: 12000,
},
]
},
},
```
Closes https://github.com/pagarme/mercurio/issues/153 
In a good pull request, everything above …
> credit_card: add function to change object installment

- public/assets/js/apiParameters.js
- src/components/Cart/Cart.test.js
- src/components/Cart/index.js
- src/containers/Checkout/index.js
- src/utils/strategies/mundipagg.js
moves the shippingRate prop from the cart object
to the shipping object and renames it to fee
Docs to review: https://docs.pagar.me/v2017-08-28/docs/novo-checkout-vers%C3%A3o-custom
Closes https://github.com/pagarme/mercurio/issues/151 
> api: move shippingRate from cart to shipping object

- src/themes/default/button/index.css
- stories/Button/index.js
Closes https://github.com/pagarme/mercurio/issues/156 
> button: update disable style

- src/themes/default/switch/index.css
- stories/Switch/index.js
Closes https://github.com/pagarme/mercurio/issues/157
> switch: change color and other styles

- src/components/Cart/Cart.test.js
- src/components/Cart/index.js
- src/containers/Checkout/CheckoutContainer.test.js
- src/containers/Checkout/index.js
- src/store.js
For better understanding, read the issue.
Closes https://github.com/pagarme/mercurio/issues/186 
> cart: fix amount

- src/pages/Payment/CreditCard.js
the transaction was not working with the creditcard payment method,
this PR fixes it
Closes https://github.com/pagarme/mercurio/issues/188
> creditcard: fix transaction flow

- src/themes/default/customerPage/index.css
Closes https://github.com/pagarme/mercurio/issues/187 
> customer_page: update mobile media

- src/components/MessageInfo/Analysis/index.js
- src/components/MessageInfo/Error/index.js
- src/themes/default/messageInfo/analysis/index.css
- src/themes/default/messageInfo/error/index.css
update the style to match the new pattern created in the analysis page
and to also work on mobile
Closes https://github.com/pagarme/mercurio/issues/165
> error-page: update style

- src/pages/Payment/Boleto.js
- src/themes/default/boletoPage/index.css
Closes https://github.com/pagarme/mercurio/issues/168
> boleto: update mobile layout

- src/components/MessageInfo/Success/index.js
- src/pages/Payment/CreditCard.js
- src/themes/default/checkout/index.css
- src/themes/default/messageInfo/success/index.css
- stories/Pages/index.js
update the style to match the new pattern in other message pages.
adds mobile version
split in two pages the stories in storybook
Closes https://github.com/pagarme/mercurio/issues/191
Closes  https://github.com/pagarme/mercurio/issues/167
> success-page: update style

- src/components/Header/index.js
- src/containers/Checkout/index.js
- src/images/navigate_back.svg
- src/themes/default/header/index.css
Add header navigation on mobile.
Closes https://github.com/pagarme/mercurio/issues/194
> header: add navigation on mobile

- src/components/Cart/Cart.test.js
- src/components/Cart/index.js
- src/themes/default/cart/index.css
Closes https://github.com/pagarme/mercurio/issues/196
> cart: update mobile layout

- src/pages/Payment/Boleto.js
Add a handle to make a billet transaction
https://github.com/pagarme/mercurio/issues/204
> Fix transaction with boleto

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
- docker/docker_bash.sh
- docker/docker_bootstrap.sh
- docker/docker_run.sh
Closes https://github.com/pagarme/mercurio/issues/207 
> project: add Docker

- src/pages/Billing.js
Closes https://github.com/pagarme/mercurio/issues/212
> billing: add state validation

- src/pages/Billing.js
Closes https://github.com/pagarme/mercurio/issues/211
> billing: add complement validation

- src/pages/Shipping.js
Closes https://github.com/pagarme/mercurio/issues/220
> shipping: add complement and state validation

- src/App.js
- src/actions/index.js
- src/containers/Checkout/index.js
- src/containers/Checkout/statechart.js
- src/index.js
- src/pages/Payment/CreditCard.js
- src/reducers/creditCard.js
- src/reducers/index.js
- src/reducers/installments.js
- src/reducers/reducers.test.js
- src/reducers/transactionValues.js
- src/store.js
- src/utils/strategies/mundipagg.js
- src/utils/strategies/pagarme.js
- src/utils/strategies/urls.js
- src/utils/validations/apiValidation.js
- src/utils/validations/index.js
Use pagarme-core branch `add/create-card-with-ek`
Closes https://github.com/pagarme/mercurio/issues/218
> Create cardId with encryption_key

- src/containers/Checkout/index.js
- src/containers/Checkout/statechart.js
- src/store.js
- src/utils/strategies/pagarme.js
- src/utils/validations/index.js
- yarn.lock
Before test this PR, review that https://github.com/pagarme/artis/pull/240
Use pagarme-core branch `add/create-card-with-ek`
Insert param `cardId` inside `configs`.
Closes https://github.com/pagarme/mercurio/issues/217
> One Click Buy: Add option

- src/components/Cart/index.js
- src/components/Header/index.js
- src/containers/Checkout/index.js
- src/reducers/transactionValues.js
- src/store.js
just fixing some minor issues, read commits for better understanding 
> Fix performance issues

- src/containers/Checkout/index.js
- src/containers/Checkout/statechart.js
- src/pages/Billing.js
- src/pages/Payment/PaymentOptions.js
- src/pages/Shipping.js
- src/reducers/pageInfo.js
Closes https://github.com/pagarme/mercurio/issues/239
> navigation: fix flow when pages are not visible

- src/components/MessageInfo/Error/index.js
- src/components/MessageInfo/Success/index.js
- src/pages/Billing.js
- src/pages/Customer.js
- src/pages/Payment/Boleto.js
- src/pages/Payment/CreditCard.js
- src/pages/Payment/PaymentOptions.js
- src/pages/Shipping.js
there are some tags that should be used only once, so we needed to
remove them
Closes https://github.com/pagarme/mercurio/issues/226 
> chore: remove repeated semantic html tags

- src/utils/strategies/pagarme.js
Closes https://github.com/pagarme/mercurio/issues/255 
> shipping: returning object on callback

- src/pages/Billing.js
- src/pages/Customer.js
- src/pages/Payment/CreditCard.js
- src/pages/Shipping.js
Closes https://github.com/pagarme/mercurio/issues/253
> pages: add focus on first input

- src/containers/Checkout/index.js
- src/utils/strategies/pagarme.js
Check if pass URL in the transaction request.
Closes https://github.com/pagarme/mercurio/issues/256
> Add url on transaction payload

- public/assets/js/panel.js
- public/assets/js/simpleParameters.js
- src/index.js
Docs para review: 
**Custom**
https://docs.pagar.me/v2017-08-28/docs/novo-checkout-vers%C3%A3o-custom
**Simples**
https://docs.pagar.me/v2017-08-28/docs/novo-checkout-vers%C3%A3o-simple
Closes https://github.com/pagarme/mercurio/issues/251
Closes https://github.com/pagarme/mercurio/issues/258
> api: update checkout open method

- src/containers/Checkout/index.js
- src/store.js
- src/utils/calculations/calcAmount.js
- src/utils/calculations/index.js
- src/utils/validations/apiValidation.js
Now the checkout calculate the amount by two ways:
* Getting `amount` prop from `transaction`
* Calc `amount` by sum and multiplication the items of cart.
Closes https://github.com/pagarme/mercurio/issues/231 
> amount: update handle amount in checkout

- public/assets/js/customParameters.js
- src/pages/Customer.js
- src/pages/Payment/CreditCard.js
- src/utils/validations/cnpj.js
- src/utils/validations/cnpj.test.js
- src/utils/validations/index.js
Adiciona o suporte ao campo CNPJ no campo `documentNumber` do cliente. 
Closes https://github.com/pagarme/mercurio/issues/221
> Adiciona suporte ao CNPJ no customer

- src/utils/strategies/pagarme.js
Closes https://github.com/pagarme/mercurio/issues/269 
> shipping: fix pagarme strategy payload

- src/utils/helpers/getCheckoutVersion.js
- src/utils/strategies/pagarme.js
Closes https://github.com/pagarme/mercurio/issues/263
> transaction: add user_agent header

- src/components/MessageInfo/Analysis/index.js
- src/components/MessageInfo/Error/index.js
- src/components/MessageInfo/Success/index.js
- src/containers/Checkout/index.js
- src/containers/Checkout/statechart.js
- src/index.js
- src/pages/Payment/Boleto.js
- src/pages/Payment/CreditCard.js
- src/pages/Payment/PaymentOptions.js
- src/utils/strategies/pagarme.js
Tracking steps and some important events.
Closes https://github.com/pagarme/mercurio/issues/248
> Tracking with analytics

- public/assets/js/customParameters.js
- src/containers/Checkout/index.js
- src/pages/Payment/CreditCard.js
* Inserted allowSaveCreditCard param to api interface;
* Returning customer,billing and shipping onSuccess callback.
Closes https://github.com/pagarme/mercurio/issues/270 
> one-click-buy: update config

- public/assets/js/customParameters.js
- src/store.js
Change the position of `cardId` on `customerParameters`.
Closes https://github.com/pagarme/mercurio/issues/271
> one-click-buy: update cardId config position

- public/assets/js/panel.js
- public/assets/js/simpleParameters.js
- src/App.js
- src/containers/Checkout/index.js
- src/index.js
- src/reducers/reducers.test.js
- src/reducers/transactionValues.js
- src/utils/helpers/getParentElement.js
No checkout simples, o usuário agora pode colocar a tag `form` no pai, e mudar o `type` do button para `submit` que o form será disparado após a transação ser em sucedida.
Closes https://github.com/pagarme/mercurio/issues/252 
> Checkout: update simple integration

- public/assets/js/customParameters.js
- public/assets/js/panel.js
- src/containers/Checkout/index.js
- src/index.js
- src/pages/Billing.js
- src/pages/Customer.js
- src/pages/Payment/Boleto.js
- src/pages/Payment/CreditCard.js
- src/pages/Payment/PaymentOptions.js
- src/pages/Shipping.js
Closes https://github.com/pagarme/mercurio/issues/261
> Add pages callbacks

- src/components/MessageInfo/Error/index.js
- src/containers/Checkout/index.js
When user clicks on back button, nothing happens.
Because the function return another function.
Closes https://github.com/pagarme/mercurio/issues/278 
> error-message: fix back button

- src/components/MessageInfo/Success/index.js
- src/themes/default/messageInfo/success/index.css
Closes https://github.com/pagarme/mercurio/issues/274
> success-page: fix order link

- src/components/MessageInfo/Success/index.js
Adjust the name.
Closes https://github.com/pagarme/mercurio/issues/285 
> chore: fix download boleto button name

- cypress/helpers/custom.js
- cypress/integration/custom/flow/back.spec.js
- cypress/integration/custom/flow/steps.spec.js
- cypress/integration/custom/pages/confirmation.spec.js
**Dependency**: https://github.com/pagarme/artis/pull/269
Closes https://github.com/pagarme/mercurio/issues/290 
> Cypress: add flow and pages tests

- src/themes/default/checkout/index.css
Ajusta o layout em desktop.
Closes https://github.com/pagarme/mercurio/issues/319
> chore: fix checkout position on desktop

- README.md
Closes https://github.com/pagarme/artis/issues/274 
> chore(readme): update "rodando" section

- package.json
- yarn.lock
Adicionando lib que verifica as versões estáveis mais novas do projeto.
Closes #XXX 
> lib: add npm-check-updates lib

- .github/CODEOWNERS
> adding ghostbusters to codeowners

- public/assets/js/customParameters.js
- src/containers/Checkout/index.js
- src/utils/strategies/pagarme.js
Re-inserting `postback` parameter.
Closes https://github.com/pagarme/mercurio/issues/326 
> postback: add on checkout

- src/containers/Checkout/index.js
Removed duplicated code.
```js
if (onSuccess) {
this.submitForm()
onSuccess(callbackPayload)
}
if (choosedPaymentType === 'boleto') {
if (onSuccess) {
onSuccess(callbackPayload)
}
return transition('TRANSACTION_ANALYSIS')
}
```
```js
if (onSuccess) {
this.submitForm()
onSuccess(callbackPayload)
}
if (choosedPaymentType === 'boleto') {
return transition('TRANSACTION_ANALYSIS')
}
```
Closes https://github.com/pagarme/mercurio/issues/327 
1. I've updated the project docs …
> callback: fix onSuccess callback all

- package.json
> package.json: update babel-core lib

- package.json
> package.json: update @babel/polyfill lib

- package.json
- yarn.lock
> package.json: update babel-jest lib

- cypress/integration/custom/api/minimal.spec.js
- cypress/integration/custom/api/transaction.spec.js
- public/assets/js/customParameters.js
- public/index.html
- src/components/MessageInfo/Error/index.js
- src/containers/Checkout/index.js
- src/utils/helpers/date.js
- src/utils/validations/apiValidation.js
- stories/Pages/index.js
Ao dar erro de uma transação com boleto mostramos mensagens do cartão de crédito.
1. Verificar o tipo de erro retornado da request de transação e exibir mensagens para cada tipo de caso - boleto ou cartão de crédito;
2. Validar o campo `expiration_at` na api do checkout customizado, para que a data informado não seja antiga.
Closes https://github.com/pagarme/tecnologia-vendas/issues/51 …
> Fix: Transaction error on boleto

- config/jest/setupTests.js
- src/index.js
Reference https://github.com/pagarme/tecnologia-vendas/issues/115
> Google Analytics: Update GA code

- README.md
> readme: remove team

- README.md
> chore: remove circleci in README
